### ISSUE TITLE
retroarch reflection shader

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#11]
Hi

I found a very interesting opensource shader for retroarch

https://forums.libretro.com/t/hsm-mega-bezel-reflection-shader-feedback-and-updates/25512

Any idea if this can be ported to 3darcade?

It's not only cool for the reflection but also for crt shader on the emulation screen.

**Comment by Skurdt** [comment]
Custom shaders are supported, provided they are written specifically for unity.

The reflections part of this is not going to work for 3d models. The crt and other effects can work.

For porting this (or other shaders), this would require a quite substantial knowledge of shader programming, which I'm not willing to delve into at this time (and for a good long while too).

External contributions to the project are welcome though...

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
