### ISSUE TITLE
executable

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#6]
Hi

Is there already a test version executable available for download, including all files it needs to run?

I'm not a developer and not able to compile it.

thx

**Comment by Skurdt** [comment]
Actually yes, the current codebase is finally at a point where most of the functionalities* are available without the unity editor.

* with some settings not available to the runtime UI (manual editing of xml files is still required).

see: https://github.com/3DArcade/3DArcade/releases/

**Comment by dreamsoftunitedkingdom** [comment]
Can you tell me where to put the roms and cores?
Do I need to copy the retroarch DLL filez of installed cores?

thx

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
