### ISSUE TITLE
feature request: add retroarch bezels

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#7]
hi

A very cool feature would be to add support for these retroarch bezels.

https://m.youtube.com/playlist?list=PL3KJBrqmANQ5g42y6KOvrt6ipPU1Qtevx

You see it's the most realistic artwork in existence for cabinets

**Comment by dreamsoftunitedkingdom** [comment]
Also cool would be mame artwork support ( in zip format) and put the textures from that zip file on the cabinet model (bezel, marquee etc)

**Comment by Skurdt** [comment]
Since these are all 2d and formatted and cropped for widescreen displays, there's no point to try and port any of these. You can setup retroarch has an external launcher and uses these as they are if you want that.

**Comment by dreamsoftunitedkingdom** [comment]
I mean of course put them as texture on the cabinet model around the emulated screen as bezel.
They are better then mame artwork.

If you support both mame artwork and retroarch bezels then you can make option to choose (which has first priority)

**Comment by Skurdt** [comment]
You'd have to show me an example of how any of the artworks from the videos would look, when applied to a mesh that is used as a bezel.
I don't see how having a flat cab render and extra cabs on the sides would fit on a 3D model.

Either way, dynamic bezels is probably not gonna happen, the majority of artworks you can find online have the screen at a different scale. This would require dynamic adjustment of position and scale of the screen mesh.

The idea of having a "cab builder mode" was discussed and is still something I want to add (choosing the different parts like side panels, bezels, monitors and buttons/sticks to make a custom cab). Then you'll be able to apply any material/image for the different parts and adjust them manually as you see fit. But for them to be calculated based on, who knows what, that's not realistically feasible.

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
