### ISSUE TITLE
feature request: blender model/scene support

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#8]
hi

Because there is no docs yet  I don't know what tool will be used to let users create cabinet models and scenes.
It would be great if we don't rely on proprietary formats like 3ds max.

If we only use an open source tool everybody can create models and scenes and this is a big advantage for 3darcade.
Also the created models are free then, which is maybe not true for proprietary formats. So as a result the free models can bedistributed online wit 3d arcade too. 

I recommend using blender (blender.org). I can find tutorials it can work in unity.

thx

**Comment by Skurdt** [comment]
You can use whatever modelling software you want. License of the program has nothing to do with the distribution of artworks.

**Comment by dreamsoftunitedkingdom** [comment]
You want to support all 3d models formats? Like max, maya, blend, ...?
It's just a waste of time I think.

**Comment by Skurdt** [comment]
Importing arbitrary 3d models, from any format, is not planned for the runtime.

You have to author your model inside of unity, prepare the marquee and screen to allow for dynamic artworks, then submit the content for it to be available as a download at runtime (downloading is not ready as a feature yet).

If I were to add runtime model parsing, it would certainly not be for 3ds or blend files. More for obj or fbx files, which you can get from any of these programs.
So again, you can you use whatever modelling software you want. Unity supports most of the common formats they can export to. Also, you can make non-free models with Blender.

**Comment by dreamsoftunitedkingdom** [comment]
What format will currently be used for user created models? FBX then?

**Comment by Skurdt** [comment]
If using substance painter or quixel mixer, then authors will most definitely use fbx.

But, like I said twice already, unity imports all the common formats fine.

The "end format" is going to be an asset bundle stored on disk, downloadable from the cloud. So no fbx, obj, blend or whatever is going to be present on the user's disk (Only the read-only binary catalog of all the data needed to display the models at runtime).

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
