### ISSUE TITLE
cross platform?

### ISSUE THREAD

**Issue by dreamsoftunitedkingdom** [3DArcade/3DArcade#9]
hi

are there plans to make it cross platform?
I think this is maybe possible using .net 6 which is coming soon and has cross platform compiler.

Which .net version is used now to compile?

**Comment by Skurdt** [comment]
Most likely but not before all the basic features are implemented, pcvr is fully integrated, and all the old models are converted

**Comment by dreamsoftunitedkingdom** [comment]
YOUR SOFTWARE FUCKING SUCKS

SUCK MY MOTHERFUCKING CLIT STUPID LOSER

JESSICA
